### ISSUE TITLE
Enemies sound wrong when turned

### ISSUE THREAD

**Issue by jackoverfull** [silverweed/lifish#10]
When you take all the coins and the Extra Game starts the enemies transform but still emit their typical sounds, not the transformed one.

**Comment by silverweed** [comment]
Thanks for your report, I fixed this in commit 1150aa62cddd7ff613e2dcb742991864fe2b0792 .

**Comment by jackoverfull** [comment]
Wonderful, thanks! Seems I'll do another run one of these days then.

Inviato da iPhone

**Comment by jackoverfull** [comment]
Hello, I just downloaded Lifish Boom 1.5.3 and it crashes on start on my system, 1.5.2 still works fine.

Here is the crash report…

Process:               lifish [15714]
Path:                  /Applications/Giochi/*/BOOM Remake.app/Contents/MacOS/lifish
Identifier:            github.com/silverweed/lifish
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           lifish [15714]
User ID:               501

Date/Time:             2022-12-26 20:50:21.097 +0100
OS Version:            Mac OS X 10.14.6 (18G9323)
Report Version:        12
Anonymous UUID:        66665C73-E884-FBF4-200D-A8EBC269742B

Sleep/Wake UUID:       0836AF92-FFB1-41F0-B43B-A695F7FB0C5B

Time Awake Since Boot: 180000 seconds
Time Since Wake:       310 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/sfml/lib/libsfml-graphics.2.5.dylib
  Referenced from: /Applications/Giochi/*/BOOM Remake.app/Contents/MacOS/lifish
  Reason: image not found

Binary Images:
       0x10f1b0000 -        0x10f296fff +github.com/silverweed/lifish (0) <53521BC1-1C42-3600-9717-73EC7BF9A283> /Applications/Giochi/*/BOOM Remake.app/Contents/MacOS/lifish
       0x11cb26000 -        0x11cb9070f  dyld (655.1.1) <4842B61A-B868-3146-9CA9-5582C4198B25> /usr/lib/dyld

Model: MacBookPro9,2, BootROM 422.0.0.0.0, 2 processors, Intel Core i5, 2,5 GHz, 8 GB, SMC 2.2f44
Graphics: kHW_IntelHD4000Item, Intel HD Graphics 4000, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x029E, 0x434D5341384758334D324131303636433720
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x029E, 0x434D5341384758334D324131303636433720
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xF5), Broadcom BCM43xx 1.0 (7.21.190.34 AirPortDriverBrcm4360-1325.3)
Bluetooth: Version 6.0.14d13, 3 services, 27 devices, 1 incoming serial ports
Network Service: iPhone, Ethernet, en4
Serial ATA Device: CT2000MX500SSD1, 2 TB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 3.0 Bus
USB Device: iPhone
Thunderbolt Bus: MacBook Pro, Apple Inc., 25.1

**Comment by stacksjb** [comment]
Please open a new issue/thread

**Comment by stacksjb** [comment]
This is the same issue documented here https://github.com/silverweed/lifish/issues/18

For some reason, when it is bundled/packaged for Mac, it doesn't have sfml included, so it fails to launch.

As a workaround, you can use Brew (https://brew.sh/) to install sfml `brew install sfml` and it will launch and function successfully

**Comment by jackoverfull** [comment]
Thank you for pointing this out, in fact those framework ARE included, just not linked correctly in the executable.
There is no need to install sfml on your own, just relinking to the correct path using install_name_tool solves the issue (XCode may be needed to do so, I'm not sure on more recent systems):

install_name_tool -change /usr/local/opt/sfml/lib/libsfml-graphics.2.5.dylib @rpath/sfml-graphics.framework/Versions/2.5.1/sfml-graphics /path/to/BOOM\ Remake.app/Contents/MacOS/lifish 
install_name_tool -change /usr/local/opt/sfml/lib/libsfml-window.2.5.dylib @rpath/sfml-window.framework/Versions/2.5.1/sfml-window /path/to/BOOM\ Remake.app/Contents/MacOS/lifish
install_name_tool -change /usr/local/opt/sfml/lib/libsfml-audio.2.5.dylib @rpath/sfml-audio.framework/Versions/2.5.1/sfml-audio /path/to/BOOM\ Remake.app/Contents/MacOS/lifish
install_name_tool -change /usr/local/opt/sfml/lib/libsfml-system.2.5.dylib @rpath/sfml-system.framework/Versions/2.5.1/sfml-system /path/to/BOOM\ Remake.app/Contents/MacOS/lifish
