### ISSUE TITLE
Enemies tend to be stuck in transporters

### ISSUE THREAD

**Issue by jackoverfull** [silverweed/lifish#11]
If you have for example a transporter at the end of a corridor that leads to another corridor enemies will often just follow those corridors all the time, even if by turning in another direction after transporting they may escape them. In the original Boom they would make the corridors a couple of times maximum, then change direction Ian’s go somewhere else. I’ve noticed this with Minotaurs in particular.

I don’t know if this is related, but all enemies seem much more active as well, roaming the map more than in the original boom. In particular the easy guys tended to remain in their areas when freed, now they go everywhere.

**Comment by silverweed** [comment]
Thanks for reporting this, I fixed the teleport issue in [9aacce7](https://github.com/silverweed/lifish/commit/9aacce72f331f5545f4781a14a5a0d87ba193e4f). I also fixed a bug where Ghosts would keep dashing indefinitely instead of resetting their attack when teleported.

**Comment by jackoverfull** [comment]
Wonderful, thanks. Looking forward to the next release.

Inviato da iPhone
