### ISSUE TITLE
icon.png is missing

### ISSUE THREAD

**Issue by bl00dy1837** [silverweed/lifish#13]
When I start the game from console i get following warning.

`Failed to load image "/usr/share/boom/assets/graphics/icon.png". Reason: Unable to open file`

It's on the code https://github.com/silverweed/lifish/blob/f2c2986fd00276eae8f6312106a47e62aeeee077/src/main.cpp#L146

**Comment by silverweed** [comment]
Thanks for spotting this, I added the icon in 9cd138ab9
