### ISSUE TITLE
Relicensing lifish

### ISSUE THREAD

**Issue by silverweed** [silverweed/lifish#3]
@bsvercl I'm opening this issue to contact you specifically, as private messages were removed from Github.

To get to the point: I'm about to close source this project. I'm glad you were interested in it enough to fork it, but I kindly ask you to delete your fork from Github so it does not remain unparented when I make this repo private.
I know you have all the rights to refuse to do so - the project is currently in GPL after all - but I'm asking this as a favor. 
You can still keep the code of course, I just ask you not to 1. upload it on the internet or 2. redistribute it verbatim, as that code is incomplete and will not receive further (public) updates from me.

Again, this is a REQUEST, I have no rights to force you to delete that repo and I won't even try to do so.

The reason behind my decision to close source lifish is that I decided to go serious with it and try to complete it and sell it. However this means paying an artist to create the game graphics/sounds/etc; you'll understand that I'd like to at least cover this cost, and unfortunately I don't think that selling an open source game is a viable option. 
I'd still like to re-open source the core engine later on, but until it's not 100% separated from the game, I'm not doing so.

Thank you for the collaboration.

**Comment by cdstanford** [comment]
I would personally donate significantly to a kickstarter or similar for your game -- but I would not purchase a closed-source game. Please reconsider :(

**Comment by silverweed** [comment]
@cdstanford Uhm, Kickstarter is an option I haven't considered so far...Are you aware of any examples of games which have successfully used this method? I'd be super-happy to be able to sell *and* keep my game open source at the same time, but I'm not sure it's a viable option...

**Comment by silverweed** [comment]
On a sidenote: I'm not sure how much it'll cost to produce the required amount of assets, but it's probably around 10^3 eur as the order of magnitude. That's admittedly not a *huge* cost, but it's still non-negligible (at least for one without an income like me). I suppose it *could* be covered via KS, though, so it may prove viable after all.

**Comment by cdstanford** [comment]
Hi silverweed,

Thanks for responding. First off, I wanted to say that I really appreciate all the time you have spent to bring a childhood game of mine, Boom, to life. Although I haven't yet figured out all of the components to get the game working on my linux laptop, I am so happy the project exist and I'm interested in helping in whatever way I can, even financially.

I am not an expert in independent game funding. So I don't know if you would be able to successfully fund the game with a kickstarter campaign. However, I admit I'm skeptical that you will be able to make money off of commercially selling a game like this anyway. Have you considered that? I'm worried that trying to go commercial with it seems like the common-sense financially better option, but might not actually be viable. There are a lot of competing games out there, and this one is not a new idea, but a re-make of an old one.

Speaking of that, I'm worried about you making money off of a re-make of a game which is the intellectual creation of Factor Software. Is that an issue you've considered?

Whatever way I can be involved or help, let me know.

Caleb

**Comment by silverweed** [comment]
Hi Caleb, 
first of all, thanks for your consideration - I'm really glad to see someone who's interested in my work.
You're right: I started this project with the objective of remaking Boom, a game that really marked my childhood, for nowadays' machines and OSes. However, several months ago I decided that, given the amount of work I've put into this, I'd rather try and develop a new, different game based on Boom's mechanics. 

The motivations for this are not only for avoiding copyright issues - a problem I've taken seriously from the start, which initially brought me to remake all the assets - but also because at one point I realized that I could make much more than the original game with the codebase I created, and the idea of exploring new possibilities was (and is today) very alluring to me.

As a matter of fact, the pre-refactor codebase (tag [0.x](https://github.com/silverweed/lifish/tree/0.x)) is a pretty much working game with almost all Boom's original mechanics (the only thing missing is the final boss). You could, say, download and build that version, replace the assets with the ones from the original game (which are very easy to extract from Boom 2.x), and play it.

Why didn't I just finish it months ago? Because I wasn't satisfied with the result: the code was a mess and it wasn't extensible at all, and there was no space for experimentation in case I wanted to add or change something, which is something I felt very important.

The game I now want to release is indeed quite different from Boom. It uses the same core mechanics, but the levels, art style, powerups, enemies and most notably bosses will be different. The major modifications I'm going to make are:  
* several enemies are going to have unique peculiarities: some can tunnel through walls, some can warp within the level without using teleports, some spawn new enemies upon death, etc.  
* all the bosses will be different. It won't be the same boss copy-pasted and repeated over and over: they'll have different AIs, different patterns and some will also move through the field.  
* some level decades will have special modifiers and effects (like [this](http://sendvid.com/gucw4l3x))  
* there will be a (very simple) "storyline" narrated through small cutscenes inbetween different areas (i.e. before and after each bossfight)  
* there will be more powerups  
* ideally I'd like to add more playable characters with different peculiarities (but this is not 100% sure, while the other points basically are)  
* and yes, I will change that crappy side panel at one point :-P

So, as you can see, much work has already been done but much more is still required, and this project is much more ambitious than the original idea of "remaking Boom" (yeah, I know the project tagline/README say otherwise, but I haven't updated those in a while).
Of course the engine *is* very Boom-compatible, and if you're interested in a perfect Boom remake it could be done, but this is not my goal anymore. If you want a perfect remake of Boom, you can just download the 0.x release, compile it and play, but I hope you can understand why, as a video game developer, I'm seeking to do more than that.

**Comment by silverweed** [comment]
I forgot to add: I'm not an expert in independent funding either, and this is my first "serious" project. It may certainly happen that I'm not gonna make money out of it, but just having it distributed to the public would be a great success for me, it'd mean I really went through the entire process and crossed the finish line almost entirely by myself :)

**Comment by cdstanford** [comment]
Thanks for all of the explanation! I will let you decide where to go with it. I would probably buy the game actually if it was proprietary :P
I hope you make an issue on this github when you have further updates, as I'd love to stay in the loop.

--caleb

**Comment by silverweed** [comment]
Sure! I'm probably not just make the repo disappear anyway...just change my main development repo and make this one's README point towards the [dev blog](https://silverweed.github.io) I'm going to open afterwards.
I'm definitely not disappearing and I'll try to share all my progress is some way ;-)

**Comment by stacksjb** [comment]
Love the comments here. First, I would like to point out that open-source and sales are definitely two different items and can co-exist quite wildly. Wolfire software posted an article about this a few years back (http://blog.wolfire.com/2010/05/Open-source-software-is-not-always-freeware)

> "As a matter of fact, the pre-refactor codebase (tag 0.x) is a pretty much working game with almost  all Boom's original mechanics (the only thing missing is the final boss). You could say, download and build that version, replace the assets with the ones from the original game (which are very easy to extract from Boom 2.x), and play it."

Could you write a tutorial, or steps, for doing this?

Kickstarter is great, but demanding, and you either have to reach a high-interest audience or have a product which is different/cool enough to gather a following. If possible, I'd say just get it made and put together yourself and just sell it via Steam.

**Comment by silverweed** [comment]
@stacksjb 
Thanks for the link, it's very interesting and definitely worth considering in my decision about licensing. Kickstarter is in fact not an easy way to go, as I'd need to create some "prizes" for the backers, and I don't have many ideas about it; in the end, I'll probably go directly to Steam.

### Getting a working 0.1 build
Since you asked, here are the steps to follow:  
1. Download the code [here](https://github.com/silverweed/lifish/releases/tag/0.x)  
2. Unzip, `cd` into it and build the project as per [the instructions](https://github.com/silverweed/lifish#building) -- ignore the warnings
3. Download [this zip file](https://drive.google.com/open?id=0B2Xa3Iom7B6vX3dMbWQwbXZIQ00) containing the original game's assets  
4. Unzip and replace the `assets` directory in the repo (downloaded in step 1) with the `assets` directory you just extracted in step 3  
5. Launch the game and enjoy

In case you cannot replicate step 2, tell me which platform you wish to play on and I'll try to get you the already-compiled binary. Right now, I only have the Linux build environment close at hand, so if you need Windows or Mac you'll have to wait a little.

**Comment by silverweed** [comment]
Update: since building on Windows may be quite annoying, I've built it myself, assets included. You can download the "full game" [here](http://goo.gl/b2Cxsz).

If you need a Linux/Mac build tell me, but in that case it'd be a bit more difficult because for those platforms I use a dynamically linked binary.

**Comment by cdstanford** [comment]
Thanks for making the build!! It works perfectly for me on windows.
--caleb

**Comment by silverweed** [comment]
I ultimately decided to relicense Lifish, keeping it open source but transitioning from the General Public License v3 to a custom user license called [Lifish License](https://github.com/silverweed/lifish/blob/master/LICENSE). It's based on the Zlib license, but adds some Lifish-specific clauses and explicitly forbids selling derivative works. It's also much more simple and straightforward than the GPL.

I hope you're ok with this solution, but I'm leaving this issue open for comments just in case.

**Comment by Adrus88** [comment]
Hello Silverweed

First of all i want to thank you, to do this work! 

I just downloaded ur *full game link* and it works on windows wuhuuu :) 

My question is, is there any opportunity to choose start at lvl (**) ? 

Like to save a progress? 

Will there be Multiplayer over Internet? (Most important thing!) 

How to support you - prebuy the game? 

Best Greetings from Switzerland 

Adrus

**Comment by silverweed** [comment]
Hello @Adrus88, thank you for the feedback! 

> My question is, is there any opportunity to choose start at lvl (**) ?
> Like to save a progress?

Yes, you can press P during the game to bring up the Pause menu from where you can save your game. Then, when launching the game, press Load Game and give that file to the dialog that will open :)

Additionally, you can press + or - to go to the next/previous level if you want to skip a level.
Finally, if you want to start directly from level N, you can launch lifish.exe from the command prompt with the following command:
```
lifish.exe -l N
```
(it's a lowercase L, not an i). That'll start you from level N.

> Will there be Multiplayer over Internet? (Most important thing!)

Unfortunately, I do not plan to add internet multiplayer, sorry.

> How to support you - prebuy the game?

Currently I have no place where you can support me, but if you're interested in Lifish, follow either this repo or [my devblog](https://silverweed.github.io/) where I'll put news about the progress of the game. I plan to eventually release it on Steam as soon as possible, which means mostly as soon as the art and sounds are done. I've found artists to work on that, but I currently have no release date yet.
When things get more definitive I'll definitely creating a better space for following the game (like a Facebook page), so please stay in touch! I promise it'll be worth the wait ;)

**Comment by Adrus88** [comment]
Many thanks for ur fast reply and explainations :) 

I really want to give u the advice of multiplayer online again ;) 
If people can play it online together - while speaking with each over voice programs - it will attract much more players, because the game is awesome. 

Maybe u reconsider that :) If not, I'm sure u will do still very good work for the game

Best regards 

Adrus :)

**Comment by silverweed** [comment]
> Maybe u reconsider that :) 

Sure, if many people will ask for that I'll definitely look into it. For now, I'd like to keep the scope of the project as narrow as possible, or I fear I'll never get to complete it.
Online multiplayer takes a really huge effort, so let's keep it for later :-)
