### ISSUE TITLE
[Boom] Missing High scores page

### ISSUE THREAD

**Issue by Irkson** [silverweed/lifish#8]
Thank you for making my childhood dreams available again! 

Everything looks perfect but I noticed one thing is missing - a high scores page. In the original version, when you finally died each player was asked for a name and their score was saved. It was later available in the "high scores" pane in the menu.

Is this something you missed or decided to skip?

Once again – amazing job!!! 👏

**Comment by silverweed** [comment]
Hi, thank you for your words :)
The high score screen is something I thought I'd do later at the time and then never actually done. I'm willing to add it, since you're interested in it, but since now I'm a bit busy with other projects that may take a while. I'll let you know when it's done!

**Comment by silverweed** [comment]
I totally forgot about this: it should be implemented in fc2770c3833f22136f9b38f3a26dab3732d0cdcd, although I *still* haven't created a new build of the game from that.
Until I release a proper update, building the game from the latest boom branch contains the change!
